(function(){var a=this,b=true,c=/xyz/.test(function(){})?/\b__super__\b/:/.*/;Class=function(d){if(this==a)return Class.extend(d)};Class.version="1.2.0";Class.extend=function(d){function e(){b&&this.init&&this.init.apply(this,arguments)}function f(i){for(var h in i)if(i.hasOwnProperty(h))e[h]=i[h]}var g=this.prototype;b=false;var j=new this;b=true;e.include=function(i){for(var h in i)if(h=="include")if(i[h]instanceof Array)for(var k=0,l=i[h].length;k<l;++k)e.include(i[h][k]);else e.include(i[h]);
else if(h=="extend")if(i[h]instanceof Array){k=0;for(l=i[h].length;k<l;++k)f(i[h][k])}else f(i[h]);else if(i.hasOwnProperty(h))j[h]=typeof i[h]=="function"&&typeof g[h]=="function"&&c.test(i[h])?function(m,n){return function(){this.__super__=g[m];return n.apply(this,arguments)}}(h,i[h]):i[h]};e.include(d);e.prototype=j;e.constructor=e;e.extend=arguments.callee;return e}})();var Dom=window.Dom={select:function(a){return a.charAt(0)=="#"?document.getElementById(a.substr(1)):document.getElementsByTagName(a)},create:function(a,b){var c=document.createElement(a),d;for(d in b)c.setAttribute(d,b[d]);return c}};Function.prototype.bind=function(a){var b=this;return function(){var c=Array.prototype.slice.call(arguments);return b.apply(a||null,c)}};function in_boundary(a,b){return a[0]>=b[0]&&a[1]>=b[1]&&a[0]<=b[2]&&a[1]<=b[3]}function in_radius(a,b,c){var d=a[0]-b[0];a=a[1]-b[1];return c*c>=d*d+a*a}function boundary_center(a){return[a[0]-(a[0]-a[2])/2,a[1]-(a[1]-a[3])/2]}function bounding_square(a,b){return[a[0],a[1]+b,a[1],a[1]+b]}
function rotate(a,b){var c=a[0],d=a[1],e=Math.sin(b),f=Math.cos(b);return[c*f-d*e,c*e+d*f]}var binary_search=function(a,b,c){var d=0,e=a.length;if(c){for(;d<e;){var f=d+e>>1;c(a[f],b)?d=f+1:e=f}return c(a[d],b)?d:~d}else{for(;d<e;){f=d+e>>1;a[f]<b?d=f+1:e=f}return a[d]==b?d:~d}},binary_insert=function(a,b,c){c=binary_search(a,b,c);if(c<0)c=~c;a.splice(c,0,b);return c},binary_remove=function(a,b,c){b=binary_search(a,b,c);return b>=0?a.splice(b,1)[0]:false};
function Cycle(a){var b=0,c=a.length;return function(){if(b==c)b=0;return a[b++]}}function CounterCallback(a,b){return function(){--a==0&&b()}}function make_grid(a,b){for(var c=[],d=0,e=a[0];d<e;d++){for(var f=[],g=0,j=a[1];g<j;g++)f.push(b([d,g]));c.push(f)}return c}function make_grid_fast(a,b){for(var c=[],d=a[1]-1,e=a[0]-1;e>=0;e--){for(var f=[],g=d;g>=0;g--)f.push(b);c.push(f)}return c}function iter_box(a,b){for(var c=a[1],d=a[2],e=a[3],f=a[0];f<d;f++)for(var g=c;g<e;g++)b([f,g])}
function iter_line(a,b,c){var d=a[0];a=a[1];var e=b[0]-d,f=b[1]-a;b=Math.abs(e);var g=Math.abs(f);e=e>0?1:-1;f=f>0?1:-1;var j=0,i=0,h;h=c([d,a]);if(h==false)return false;for(;j<b||i<g;){h=(1+2*j)*g-(1+2*i)*b;if(h==0){if(j<b){h=c([d+e,a]);if(h==false)return false}if(i<g){h=c([d,a+f]);if(h==false)return false}d+=e;a+=f;j++;i++}else if(h<0){d+=e;j++}else{a+=f;i++}h=c([d,a]);if(h==false)return false}}
function draw_grid_to_ctx(a,b,c){b.fillStyle="rgb(255,255,255)";iter_box(c,function(d){a[d[0]][d[1]]&&b.fillRect(d[0],d[1],1,1)})}function ctx_xy_to_rgb(a,b){var c=a.getImageData(b[0],b[1],1,1);return[c.data[0],c.data[1],c.data[2]]}function flat_idx(a,b){return b[0]*a[0]*a[2]+b[1]*a[2]+b[2]}function message(a){if(message._target===undefined)message._target=document.getElementById("messages");message._target.innerHTML=a;return message}
function inverse_lookup(a){var b={},c;for(c in a)b[a[c]]=c;return b};var Clock=Class({init:function(){this.num_ticks=0;this.time_ticked=Clock.now},tick:function(){var a=Clock.now-this.time_ticked;this.time_ticked=Clock.now;this.num_ticks++;return a},delta:function(){return Clock.now-this.time_ticked}});Clock.update=function(){Clock.now=+new Date};Clock.update();var CircleEntity=function(a,b){this.pos=a;this.radius=b},BoxEntity=function(a){this.box=a},PositionCollider=function(a){this.size=a};
PositionCollider.prototype={init:function(){this.grid=make_grid_fast(this.size,0)},set:function(a,b){this.grid[a[0]][a[1]]=b},set_box:function(a,b){for(var c=a[1],d=a[2],e=a[3],f=this.grid,g=a[0];g<d;g++)for(var j=c;j<e;j++)f[g][j]=b},set_from_canvas:function(a,b){var c=b[0],d=b[1],e=b[2],f=b[3],g=a.getImageData(c,d,e-c,f-d).data,j=this.grid,i=3;for(d=d;d<f;d++)for(var h=c;h<e;h++){j[h][d]=g[i]==255;i+=4}},get:function(a){return this.grid[a[0]][a[1]]!=false}};
var EntityCollider=function(a){this.size=a};
EntityCollider.prototype={init:function(){this.circles=[];this.boxes=[];this.collider=new PositionCollider(this.size);this.collider.init()},add:function(a){if(a.box)this.boxes.push(a);else a.pos&&a.radius&&this.circles.push(a)},remove:function(a){for(var b=this.boxes,c=b.length-1;c>=0;c--)if(a==b[c]){b.splice(c,1);return true}b=this.circles;for(c=b.length-1;c>=0;c--)if(a==b[c]){b.splice(c,1);return true}},get:function(a){if(!this.collider.get(a))return false;for(var b=this.boxes,c=b.length-1;c>=0;c--){var d=
b[c];if(in_boundary(a,d.box))return d}return true}};var Input=Class({bindings:{},pressed:{},queued:{},_handler_keydown:null,_handler_keyup:null,init:function(){var a=this;this._handler_keydown=function(b){a.keydown(b)};this._handler_keyup=function(b){a.keyup(b)};this.start_listening()},start_listening:function(){window.addEventListener("keydown",this._handler_keydown,false);window.addEventListener("keyup",this._handler_keyup,false)},stop_listening:function(){window.removeEventListener("keydown",this._handler_keydown);window.removeEventListener("keyup",
this._handler_keyup)},bind_listen:function(a){function b(d){c.bindings[d.keyCode]=a;d.stopPropagation();d.preventDefault();window.removeEventListener("keydown",b);c.start_listening()}this.stop_listening();var c=this;window.addEventListener("keyup",b,false)},keydown:function(a){var b=this.bindings[a.keyCode];if(b){this.pressed[b]=true;a.stopPropagation();a.preventDefault()}else(a=this.queued[a.keyCode])&&a.pop()()},keyup:function(a){var b=this.bindings[a.keyCode];if(b){this.pressed[b]=false;a.stopPropagation();
a.preventDefault()}},bind:function(a){for(var b in a)this.bindings[b]=a[b]},queue:function(a,b){if(this.bindings[a])throw Error("One-time bind must be an unassigned key.");var c=this.queued[a]||[];c.push(b);this.queued[a]=c}});
Input.KEY_CODES={8:"BACKSPACE",9:"TAB",13:"ENTER",16:"SHIFT",17:"CTRL",18:"ALT",19:"PAUSE",20:"CAPS_LOCK",27:"ESC",32:"SPACE",33:"PAGE_UP",34:"PAGE_DOWN",35:"END",36:"HOME",37:"LEFT_ARROW",38:"UP_ARROW",39:"RIGHT_ARROW",40:"DOWN_ARROW",44:"PRINT_SCREEN",45:"INSERT",46:"DELETE",48:"0",49:"1",50:"2",51:"3",52:"4",53:"5",54:"6",55:"7",56:"8",57:"9",63:"?",65:"A",66:"B",67:"C",68:"D",69:"E",70:"F",71:"G",72:"H",73:"I",74:"J",75:"K",76:"L",77:"M",78:"N",79:"O",80:"P",81:"Q",82:"R",83:"S",84:"T",85:"U",
86:"V",87:"W",88:"X",89:"Y",90:"Z",91:"META",93:"CONTEXT_MENU",96:"NUM_0",97:"NUM_1",98:"NUM_2",99:"NUM_3",100:"NUM_4",101:"NUM_5",102:"NUM_6",103:"NUM_7",104:"NUM_8",105:"NUM_9",106:"NUM_*",107:"NUM_+",109:"NUM_-",110:"NUM_PERIOD",111:"NUM_DIVISION",112:"F1",113:"F2",114:"F3",115:"F4",116:"F5",117:"F6",118:"F7",119:"F8",120:"F9",121:"F10",122:"F11",123:"F12",144:"NUMLOCK",186:":",189:"-",187:"=",188:",",190:".",191:"/",192:"APOSTROPHE",222:"'",219:"[",220:"\\",221:"]",224:"WIN_KEY"};function Player(a){this.speed=8;this.turn_rate=this.speed/5.5;this.num_deaths=this.num_wins=this.max_time_alive=this.angle=0;this.pos=[0,0];this.reset();this.color=a.color||"rgb(255,255,255)";this.name=a.name||"Anonymous";this.controls=a.controls}
Player.prototype={reset:function(a,b){this.is_active=true;this.pos=a||[100+Math.random()*440,100+Math.random()*280];this.angle=b===undefined?Math.random()*2:b;this.move_buffer=null;this.score=0},move:function(a,b,c){if(this.move_buffer)if(this.move_buffer=="left")this.angle-=this.turn_rate*c/1E3;else if(this.move_buffer=="right")this.angle+=this.turn_rate*c/1E3;var d=this.get_pos(),e=this.pos[0],f=this.pos[1];c=rotate([this.speed*c/100,0],this.angle*Math.PI);this.pos=[e+c[0],f+c[1]];var g=this.get_pos(),
j=this;if(!(g[0]==d[0]&&g[1]==d[1])){if(in_boundary(g,[0,0,b.size[0]-1,b.size[1]-1])){if(this.is_active){var i=b.state.entity_collider.collider;iter_line(d,g,function(h){if(h[0]==d[0]&&h[1]==d[1])return true;var k=b.is_collision(h);if(!k){i.set(h,true);return true}if(k===true){j.is_active=false;$(window).trigger("die",[j,Player.EVENTS.COLLIDED]);g=j.new_post=h;return false}return k.do_collision(j,a)})}}else{this.is_active=false;$(window).trigger("die",[j,Player.EVENTS.FALL_OFF])}a.strokeStyle=this.color;
a.lineWidth=1.5;a.beginPath();a.moveTo(d[0],d[1]);a.lineTo(g[0],g[1]);a.stroke();return{old_pos:d,new_pos:g,color:this.color,active:this.is_active}}},get_pos:function(){return[Math.round(this.pos[0]),Math.round(this.pos[1])]}};Player.CONTROL_KEYS=["left","right"];
Player.TEMPLATE_LIST=[{color:"rgb(150,30,20)",name:"Red Player",controls:{left:37,right:39}},{color:"rgb(40,70,140)",name:"Blue Player",controls:{left:65,right:83}},{color:"rgb(20,140,50)",name:"Green Player",controls:{left:75,right:76}},{color:"rgb(160,140,30)",name:"Yellow Player",controls:{left:101,right:103}}];Player.EVENTS={FALL_OFF:1,COLLIDED:2,ESCAPED:3,SURVIVED:4};var EntityAnimator=function(){this.time_drawn=+new Date;this.init()};EntityAnimator.prototype={init:function(){this.entities=[]},add:function(a){this.entities.push(a)},remove:function(a){for(var b=this.entities,c=b.length-1;c>=0;c--)if(a==b[c]){b.splice(c,1);return true}},draw:function(a,b){for(var c=this.entities,d=c.length-1;d>=0;d--){var e=c[d];if(!(e.time_drawn&&b-e.time_drawn<e.draw_rate)){e.draw(a);e.time_drawn=b}}this.time_drawn=b}};
function EndEntity(a){this.box=a;this.center=boundary_center(a);this.length=Math.max(a[2]-a[0],a[3]-a[1])}
EndEntity.prototype={is_collidable:true,draw:function(a){var b=this.box,c=this.center;c=a.createRadialGradient(c[0],c[1],0,c[0],c[1],this.length);c.addColorStop(0,"rgb(0,0,0)");c.addColorStop(0.4,"rgb(230,170,0)");c.addColorStop(0.9,"rgb(0,0,0)");a.fillStyle=c;a.fillRect(b[0],b[1],b[2]-b[0],b[3]-b[1]);a.strokeStyle="rgba(0,0,0,0.8)";a.strokeWidth=1;a.strokeRect(b[0],b[1],b[2]-b[0],b[3]-b[1]);return true},is_collision:function(a){return in_boundary(a,this.box)},do_collision:function(a){a.is_active=
false;a.score+=1E3;$("#score").text(a.score);$(window).trigger("win",[a,Player.EVENTS.ESCAPED]);return false}};function BonusEntity(a){this.pos=a;this.radius=6;this.box=this.get_boundary();this.is_active=true;this.is_drawn=false}
BonusEntity.prototype={is_collidable:true,is_collision:function(a){return in_boundary(a,this.box)},do_collision:function(a,b){if(this.is_active){this.is_active=false;a.score+=100;message("Yum.");$("#score").text(a.score);this.clear(b)}},get_boundary:function(){var a=this.pos[0],b=this.pos[1],c=this.radius;return[a-c,b-c,a+c,b+c]},draw:function(a){var b=this.pos[0],c=this.pos[1],d=this.radius;a.beginPath();a.arc(b,c,d-0.5,0,Math.PI*2);a.closePath();a.fillStyle="rgb(190,10,10)";a.strokeStyle="rgb(120,0,0)";
a.lineWidth=1;a.fill();a.stroke();a.fillStyle="rgb(225,150,150)";a.fillRect(b-d*0.6,c-d*0.6,2,2)},clear:function(a){var b=this.get_boundary();a.clearRect(b[0],b[1],b[2]-b[0],b[3]-b[1])}};function Level(a){this.src=a.url;this.img=new Image;this.config=a;this.name=a.name;this.description=a.description;this.min_players=a.min_players||0;this.max_players=Math.min(a.min_players||4,this.min_players);this.is_deathmatch=a.is_deathmatch||false;this.size=[640,480];this.unload()}Level.last_loaded=null;
Level.prototype={unload:function(){this.is_loaded=false;this.state=null},load:function(a,b,c){this.size=b;Level.last_loaded&&Level.last_loaded!=this&&Level.last_loaded.unload();var d=this,e=function(){var f=a.level;f.clearRect(0,0,b[0],b[1]);f.drawImage(d.img,0,0);if(!d.is_loaded){d.is_loaded=true;d.state=new LevelState(b,d.config.entities,a)}c!==undefined&&c()};if(this.img.src)e();else{this.img.src=this.src;this.img.onload=e}Level.last_loaded=d},is_collision:function(a){if(this.state.level_collider.get(a))return true;
return this.state.entity_collider.get(a)}};function LevelState(a,b,c){this.size=a;this.entities=b;this.contexts=c;this.entity_collider=new EntityCollider(this.size);this.level_collider=new PositionCollider(this.size);this.level_collider.init();this.level_collider.set_from_canvas(c.level,[0,0,this.size[0],this.size[1]]);this.reset()}
LevelState.prototype={load_entities:function(){var a=this.entities;if(a)for(var b=this.contexts.entities,c=a.length-1;c>=0;c--){var d=a[c];switch(d.type){case "START":this.start_positions.push({pos:d.pos,angle:d.angle});break;case "END":this.is_deathmatch=false;d=new EndEntity(d.box);this.entity_collider.add(d);d.draw(b);this.entity_collider.collider.set_box(d.box);break;case "BONUS":d=new BonusEntity(d.pos);this.entity_collider.add(d);d.draw(b);this.entity_collider.collider.set_box(d.get_boundary())}}},
reset:function(){this.start_positions=[];this.is_deathmatch=true;this.score=0;this.contexts.entities.clearRect(0,0,this.size[0],this.size[1]);this.entity_collider.init();this.load_entities()}};function LevelPack(a,b,c){this.name=a;this.levels=b;this.current_level=0;this.mode=c||LevelPack.MODES.NORMAL}LevelPack.MODES={NORMAL:0,LOOP:1,RANDOM:2};
LevelPack.prototype={next:function(){if(this.current_level>=this.levels.length-1)if(this.mode==LevelPack.MODES.NORMAL)return false;else if(mode==LevelPack.MODES.LOOP)this.current_level=0;if(this.mode==LevelPack.MODES.RANDOM)this.current_level=Math.floor(Math.random()*(this.levels.length-1));else this.current_level++;return this.levels[this.current_level]},first:function(){this.current_level=0;return this.levels[this.current_level]}};function Hud(a,b){this.game=a;this.target=$(b);this.packs=[];this.active=false;var c=this;this.logo=$("h1:first").click(function(){if(c.active){if(c.game.is_fresh){c.hide();c.game.resume()}}else{c.game.pause();c.show("packs")}})}
Hud.prototype={add_pack:function(a){this.packs.push(a)},draw:function(){var a=$(this.target).empty(),b=this.game,c=$('<div id="description" class="state"></div>').hide();this.description=$(c).appendTo(a);var d=this,e=$('<div id="packs" class="state"></div>').hide();$(this.packs).each(function(f,g){e.append("<h2>"+g.name+"</h2>");var j=$("<ol></ol>");$(g.levels).each(function(i,h){$("<li>"+h.name+"</li>").click(function(){b.is_ready=false;message("Loading.");b.load_level(h,function(){if(h.description){$(c).html(h.description);
d.show("description")}else{$(c).html("");d.hide()}b.is_ready=true;b.reset();b.continue_fn=b.resume;message("Ready? Press <em>Space</em> to start.")})}).appendTo(j)});e.append(j)});this.packs_menu=$(e).appendTo(a)},show:function(a){$(".state",this.target).hide();this.active=$("#"+a+".state",this.target).show();$(this.target).show();a=="packs"?$(this.logo).addClass("active"):$(this.logo).removeClass("active")},hide:function(){this.active=false;$(this.target).hide();$(this.logo).removeClass("active")}};var Game=Class({container:null,layers:[],init:function(a,b){this.container=a.element;for(var c={width:a.width,height:a.height},d=b||1;d--;){var e=Dom.create("canvas",c);this.layers.push(e.getContext("2d"));this.container.appendChild(e)}}});function set_touch_start_label(a){$("#touch-start").text(a).attr("aria-label",a)}function set_touch_start_visible(a){$("#touch-start").css("visibility",a?"visible":"hidden").attr("aria-hidden",a?"false":"true")}
function set_touch_turn_color(a){a&&$("#touch-left, #touch-right").css({"background-color":a.color,"border-color":a.color,color:"#fff"})}
function LineRageGame(a){this.contexts={level:a["static"].getContext("2d"),entities:a.dynamic.getContext("2d")};this.contexts.entities.lineWidth=1.5;this.size=[a["static"].width,a["static"].height];this.players=[];this.num_active=this.num_players=this.players.length;this.num_end=Math.min(1,this.num_players-1);this.is_fresh=this.is_ready=false;this.is_ended=this.is_paused=true;this.level=this.levelpack=this.time_started=this.time_last_tick=this.loop=null;var b=this,c=0,d=this.contexts.entities,e=function(){var f=
+new Date,g=f-b.time_last_tick,j=[];if(!b.is_paused){for(var i=0;i<b.num_players;i++){var h=b.players[i];if(h.is_active)(h=h.move(d,b.level,g))&&j.push(h)}b.time_last_tick=f;c++;b.multiplayer&&b.multiplayer.after_tick&&b.multiplayer.after_tick(j)}};this.game_loop=function(){e();stats!==undefined&&stats.update()};this.continue_fn=this.reset;window.onkeydown=function(f){if(b.multiplayer&&b.multiplayer.handle_key&&b.multiplayer.handle_key(f,true))return false;if(f.which==32)return b.continue_fn();if(f=
b._controls_cache[f.which]){f[0].move_buffer=f[1];e()}};window.onkeyup=function(f){if(b.multiplayer&&b.multiplayer.handle_key&&b.multiplayer.handle_key(f,false))return false;if(f.which!=32)if((f=b._controls_cache[f.which])&&f[0].move_buffer==f[1]){f[0].move_buffer=null;e()}};this.add_player();$(window).bind("win",function(f,g,j){f.stopPropagation();b.end();g.num_wins++;g.max_time_alive=Math.max(g.max_time_alive,b.time_last_tick-b.time_started);j==Player.EVENTS.ESCAPED?message(g.name+" escaped successfully!"):
message(g.name+" wins!");if(b.levelpack){var i=b.levelpack.next();if(!i){message("Winner is you.");return false}b.continue_fn=function(){message("Loading.");b.load_level(i,function(){b.is_ready=true;b.reset();message("Ready?");b.continue_fn=b.resume})}}else b.continue_fn=function(){hud.show("packs");b.continue_fn=function(){b.reset();hud.show("description");message("Ready?");b.continue_fn=b.resume}};return false}).bind("die",function(f,g,j){f.preventDefault();f.stopPropagation();b.num_active--;g.is_active=
false;g.max_time_alive=Math.max(g.max_time_alive,b.time_last_tick-b.time_started);g.num_deaths++;if(b.num_active<=b.num_end){$(window).trigger("lose",[g,j]);return false}if(j==Player.EVENTS.FALL_OFF)message(g.name+" fell off. lol!");else j==Player.EVENTS.COLLIDED?message(g.name+" collided."):message(g.name+" died.");return false}).bind("lose",function(f,g,j){if(b.level.is_deathmatch){f=b.players;for(g=f.length-1;g>=0;g--)if(f[g].is_active){$(window).trigger("win",[f[g],Player.EVENTS.SURVIVED]);return}}else if(b.num_players>
1)message("Complete failure.");else j==Player.EVENTS.COLLIDED||j==Player.EVENTS.FALL_OFF?message("You died."):message("You lose.");b.end();return false})}
LineRageGame.prototype={pause:function(){clearInterval(this.loop);message("Paused.");this.is_paused=true;this.continue_fn=this.resume;this.multiplayer&&this.multiplayer.on_pause&&this.multiplayer.on_pause()},resume:function(){hud.hide();message("");set_touch_start_visible(false);this.is_paused=false;this.continue_fn=this.pause;this.is_fresh=false;this.time_last_tick=+new Date;this.loop=setInterval(this.game_loop,1E3/30);this.multiplayer&&this.multiplayer.on_resume&&this.multiplayer.on_resume()},end:function(){clearInterval(this.loop);
this.is_paused=this.is_ended=true;set_touch_start_label("Ready?");set_touch_start_visible(true);var a=this;this.continue_fn=function(){a.reset();hud.show("description");message("Ready?");a.continue_fn=a.resume};this.multiplayer&&this.multiplayer.on_end&&this.multiplayer.on_end()},reset:function(){if(this.is_ready){for(var a=this.level.state.start_positions,b=0;b<this.num_players;b++){var c=a[b]||{};this.players[b].reset(c.pos,c.angle)}this.time_started=+new Date;this.num_active=this.num_players;this.is_ended=
false;set_touch_start_label("Ready?");set_touch_turn_color(this.players[0]);set_touch_start_visible(true);this.continue_fn=this.pause;this.is_fresh=true;this._refresh_game_conditions();this.level.state.reset();$("#score").text("0");this.multiplayer&&this.multiplayer.on_reset&&this.multiplayer.on_reset()}},add_player:function(){if(!(!this.is_ended||this.num_players>=4)){this.players.push(new Player(Player.TEMPLATE_LIST[this.num_players]));this.num_players=this.players.length;this._refresh_controls_cache()}},
remove_player:function(){if(!(!this.is_ended||this.num_players<=1)){this.players.pop();this.num_players=this.players.length;this._refresh_controls_cache()}},set_player_count:function(a){for(a=Math.max(1,Math.min(4,a));this.players.length<a;)this.players.push(new Player(Player.TEMPLATE_LIST[this.players.length]));for(;this.players.length>a;)this.players.pop();this.num_players=this.players.length;this._refresh_controls_cache();this._refresh_game_conditions()},_refresh_game_conditions:function(){this.num_end=
this.level.is_deathmatch?Math.min(1,this.num_players-1):0},load_level:function(a,b){this.end();var c=this;this.level=a;a.load(this.contexts,this.size,function(){for(var d=0;c.num_players<a.min_players&&d<5;d++)c.add_player();for(d=0;c.num_players>a.max_players&&d<5;d++)c.remove_player();b!==undefined&&b.call(this)})},_refresh_controls_cache:function(){for(var a={},b=0,c=this.players.length;b<c;b++)for(var d=this.players[b],e=0,f=Player.CONTROL_KEYS.length;e<f;e++){var g=Player.CONTROL_KEYS[e];a[d.controls[g]]=
[d,g]}this._controls_cache=a}};function Multiplayer(a){this.game=a;this.role="offline";this.hostConn=this.peer=null;this.conns=[];this.localIndex=0;this.maxPlayers=4;this.tick=0;this.ready=false;this.onlineLevel=new Level({name:"Online Deathmatch",url:"levels/deathmatch/blank.png",description:"",is_deathmatch:true,max_players:4,min_players:1});this.draw_ui();this.autojoin_from_hash()}Multiplayer.PROTOCOL=1;
Multiplayer.prototype={draw_ui:function(){var a=this,b=$('<div id="network"></div>');b.append('<div id="net-controls"><button id="net-host">Host Game</button><button id="net-copy" class="online-only">Copy Invite</button><input id="net-link" class="online-only" readonly="readonly" aria-label="Invite link" title="Click to select invite link" placeholder="Invite link" /></div>');b.append('<div id="net-meta"><span id="net-room" class="online-only">Room: \u2014</span><span id="net-players">Joined: 1/4</span><span id="net-status">Offline hotseat mode.</span></div>');
$("#content").prepend(b);$("#net-host").click(function(){a.host()});$("#net-copy").click(function(){a.copy_link()});$("#net-link").focus(function(){this.select()});$("#net-link").click(function(){this.select()})},set_status:function(a){$("#net-status").html(a)},joined_count:function(){return this.role=="host"?this.conns.length+1:this.game.num_players},player_label:function(a){return a==1?"1 player":a+" players"},random_token:function(){var a="";if(window.crypto&&window.crypto.getRandomValues){var b=
new Uint8Array(8);window.crypto.getRandomValues(b);for(var c=0;c<b.length;c++)a+="abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789".charAt(b[c]%57)}else for(b=0;b<8;b++)a+="abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789".charAt(Math.floor(Math.random()*57));return a},invite_url:function(a){return location.href.replace(/#.*$/,"")+"#join="+encodeURIComponent(a)},set_room_code:function(a){$("#net-room").html("Room: "+a)},update_lobby:function(a){var b=this.joined_count();$("#net-players").html("Joined: "+
b+"/"+this.maxPlayers);if(this.role=="host"){set_touch_start_label("Start");this.set_status("Red host. Share link, then Start.")}else a&&this.set_status(a)},copy_link:function(){var a=$("#net-link").val();if(a){var b=this,c=function(){$("#net-copy").text("Copied");b.set_status("Invite copied.")};if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(a).then(c,function(){b.set_status("Copy failed. Select the invite link.")});else{$("#net-link")[0].select();document.execCommand&&
document.execCommand("copy")?c():this.set_status("Invite selected.")}}},host:function(){if(typeof Peer==="undefined")this.set_status("PeerJS failed to load. Check your network connection.");else{var a=this;this.role="host";this.localIndex=0;$("#network").addClass("online");$("#net-copy").text("Copy Invite");this.peer=new Peer(this.random_token());this.peer.on("open",function(b){a.set_room_code(b);$("#net-link").val(a.invite_url(b));a.update_lobby();a.prepare_online_game(function(){a.ready=true})});
this.peer.on("connection",function(b){a.accept(b)});this.peer.on("error",function(b){b&&b.type=="unavailable-id"?a.set_status("Room token taken. Try Host Game again."):a.set_status("Host error: "+b)})}},autojoin_from_hash:function(){var a=String(location.hash||"").match(/join=([^&]+)/);a&&this.join(decodeURIComponent(a[1]))},join:function(a){if(typeof Peer==="undefined")this.set_status("PeerJS failed to load. Check your network connection.");else{var b=this;this.role="guest";$("#network").addClass("online");
$("#net-copy").text("Copy Invite");this.set_room_code(a);$("#net-link").val(this.invite_url(a));set_touch_start_label("Ready?");this.peer=new Peer;this.peer.on("open",function(){b.set_status("Connecting to host...");b.hostConn=b.peer.connect(a,{reliable:true});b.hostConn.on("open",function(){b.send(b.hostConn,{type:"hello",protocol:Multiplayer.PROTOCOL})});b.hostConn.on("data",function(c){b.receive_from_host(c)});b.hostConn.on("close",function(){b.set_status("Disconnected from host.")});b.hostConn.on("error",
function(c){b.set_status("Connection error: "+c)})});this.peer.on("error",function(c){b.set_status("Join error: "+c)})}},accept:function(a){var b=this;a.playerIndex=null;a.on("open",function(){if(!b.game.is_paused||!b.game.is_fresh){b.send(a,{type:"started"});a.close()}else if(b.conns.length>=b.maxPlayers-1){b.send(a,{type:"full"});a.close()}else{a.playerIndex=b.next_player_index();b.conns.push(a);b.send(a,{type:"welcome",protocol:Multiplayer.PROTOCOL,playerIndex:a.playerIndex,players:b.conns.length+
1,maxPlayers:b.maxPlayers,snapshot:b.snapshot()});b.broadcast_lobby();b.update_lobby()}});a.on("data",function(c){!c||typeof c.type!=="string"||c.type=="input"&&a.playerIndex!==null&&b.apply_input(a.playerIndex,c.move)});a.on("close",function(){for(var c=b.conns.length-1;c>=0;c--)b.conns[c]==a&&b.conns.splice(c,1);if(a.playerIndex!==null&&b.game.players[a.playerIndex]){b.apply_input(a.playerIndex,null);b.game.players[a.playerIndex].is_active=false}b.broadcast_lobby();b.update_lobby()})},next_player_index:function(){for(var a=
1;a<this.maxPlayers;a++){for(var b=false,c=0;c<this.conns.length;c++)if(this.conns[c].playerIndex==a)b=true;if(!b)return a}return this.conns.length+1},prepare_online_game:function(a){var b=this;this.game.is_ready=false;this.game.load_level(this.onlineLevel,function(){b.game.is_ready=true;b.game.set_player_count(b.maxPlayers);b.game.reset();b.game.continue_fn=function(){return b.start_game()};b.role=="host"?set_touch_start_label("Start"):set_touch_start_label("Ready?");hud.hide();message("");a&&a()})},
start_game:function(){if(this.role!="host")return false;var a=this.joined_count();this.game.set_player_count(a);this.game.reset();this.game.continue_fn=this.game.resume;this.set_status("Started: "+this.player_label(a)+".");return this.game.resume()},broadcast_lobby:function(){this.broadcast({type:"lobby",players:this.conns.length+1,maxPlayers:this.maxPlayers})},handle_key:function(a,b){if(this.role=="offline")return false;if(a.which==32){if(this.role=="guest"){a.preventDefault();return true}return false}var c=
null;if(a.which==37||a.which==65)c="left";else if(a.which==39||a.which==68)c="right";else return false;this.handle_move(c,b);a.preventDefault();return true},handle_move:function(a,b){if(this.role=="offline")return false;b||(a=null);if(this.role=="guest"){this.apply_input(this.localIndex,a);this.send(this.hostConn,{type:"input",move:a})}else this.role=="host"&&this.apply_input(0,a);return true},apply_input:function(a,b){var c=this.game.players[a];if(c)c.move_buffer=b},send:function(a,b){a&&a.open&&
a.send(b)},broadcast:function(a){for(var b=0;b<this.conns.length;b++)this.send(this.conns[b],a)},on_reset:function(){this.role=="host"&&this.broadcast({type:"reset",snapshot:this.snapshot()})},on_resume:function(){this.role=="host"&&this.broadcast({type:"resume",snapshot:this.snapshot()})},on_pause:function(){this.role=="host"&&this.broadcast({type:"pause"})},on_end:function(){if(this.role=="host"){var a=this;setTimeout(function(){set_touch_start_label("Start");a.game.continue_fn=function(){return a.start_game()};
a.broadcast({type:"end",snapshot:a.snapshot(),message:$("#messages").html()})},0)}},after_tick:function(a){this.role!="host"||!a||!a.length||this.broadcast({type:"tick",tick:++this.tick,segments:a,snapshot:this.snapshot()})},snapshot:function(){for(var a=[],b=0;b<this.game.players.length;b++){var c=this.game.players[b];a.push({pos:[c.pos[0],c.pos[1]],angle:c.angle,active:c.is_active,move:c.move_buffer,score:c.score,deaths:c.num_deaths,wins:c.num_wins})}return{paused:this.game.is_paused,ended:this.game.is_ended,
players:a}},apply_snapshot:function(a){if(a&&a.players){this.game.set_player_count(a.players.length);for(var b=this.game.num_active=0;b<a.players.length;b++){var c=a.players[b],d=this.game.players[b];if(d&&c){d.pos=[c.pos[0],c.pos[1]];d.angle=c.angle;d.is_active=c.active;d.move_buffer=c.move;d.score=c.score||0;d.num_deaths=c.deaths||0;d.num_wins=c.wins||0;d.is_active&&this.game.num_active++}}this.game.is_paused=a.paused;this.game.is_ended=a.ended;set_touch_turn_color(this.game.players[this.localIndex]);
$("#net-players").html("Joined: "+a.players.length+"/"+this.maxPlayers)}},receive_from_host:function(a){if(!(!a||typeof a.type!=="string"))if(a.type=="full")this.set_status("Room is full.");else if(a.type=="started")this.set_status("Game already started. Ask the host for a new room.");else if(a.type=="welcome"){this.localIndex=a.playerIndex;var b=this;this.prepare_online_game(function(){b.apply_snapshot(a.snapshot);b.ready=true;set_touch_start_label("Ready?");$("#net-players").html("Joined: "+a.players+
"/"+a.maxPlayers);b.set_status(b.game.players[b.localIndex].name+". Waiting.")})}else if(a.type=="lobby"){var c=this.game.players[this.localIndex];c=c?c.name:"Player "+(this.localIndex+1);set_touch_start_label("Ready?");$("#net-players").html("Joined: "+a.players+"/"+a.maxPlayers);this.set_status(c+". Waiting.")}else if(a.type=="reset"){b=this;this.prepare_online_game(function(){b.apply_snapshot(a.snapshot)})}else if(a.type=="resume"){hud.hide();message("");set_touch_start_visible(false);this.apply_snapshot(a.snapshot);
c=(c=this.game.players[this.localIndex])?c.name:"Player "+(this.localIndex+1);this.set_status("Playing: "+c+".")}else if(a.type=="pause"){message("Host paused.");this.game.is_paused=true}else if(a.type=="end"){this.apply_snapshot(a.snapshot);this.game.is_paused=true;set_touch_start_label("Ready?");set_touch_start_visible(true);a.message&&message(a.message)}else if(a.type=="tick"){this.draw_segments(a.segments);this.apply_snapshot(a.snapshot)}},draw_segments:function(a){for(var b=this.game.contexts.entities,
c=0;c<a.length;c++){var d=a[c];if(!(!d||!d.old_pos||!d.new_pos)){b.strokeStyle=d.color;b.lineWidth=1.5;b.beginPath();b.moveTo(d.old_pos[0],d.old_pos[1]);b.lineTo(d.new_pos[0],d.new_pos[1]);b.stroke()}}}};function TouchControls(a){this.game=a;this.rightActive=this.leftActive=false;this.bind()}
TouchControls.prototype={bind:function(){var a=this;this.bind_button("#touch-left","left");this.bind_button("#touch-right","right");$("#touch-start").bind("touchstart mousedown",function(b){a.stop_event(b);a.start_or_pause()})},bind_button:function(a,b){var c=this,d=$(a);d.bind("touchstart mousedown",function(e){c.stop_event(e);c.set_move(b,true)});d.bind("touchend touchcancel mouseup mouseleave",function(e){c.stop_event(e);c.set_move(b,false)})},stop_event:function(a){a&&a.preventDefault&&a.preventDefault();
a&&a.stopPropagation&&a.stopPropagation();return false},start_or_pause:function(){if(this.game.multiplayer&&this.game.multiplayer.role=="guest"){message("Waiting.");return false}return this.game.continue_fn()},set_move:function(a,b){if(this.game.multiplayer&&this.game.multiplayer.role!="offline")this.game.multiplayer.handle_move(a,b);else{var c=this.game.players[0];if(c)c.move_buffer=b?a:null}!this.game.is_paused&&this.game.game_loop&&this.game.game_loop()}};var game,hud,stats,multiplayer,touchControls,levelpacks=[];
$(document).ready(function(){function a(b){if(b.manifest){for(var c=[],d=0,e=b.manifest.levels.length;d<e;d++)c.push(new Level(b.manifest.levels[d]));b=new LevelPack(b.name,c);hud.add_pack(b)}}$("body").disableTextSelect();game=new LineRageGame({"static":document.getElementById("static_canvas"),dynamic:document.getElementById("dynamic_canvas")});hud=new Hud(game,$("#hud"));a({name:"Singleplayer Puzzles",manifest:{levels:[{name:"White Level",url:"levels/easy/white.png",description:"<p>Use the arrow keys (left and right) to maneuver your line to the yellow portal.</p><p>Don't hit things. Try to get the delicious red circles for bonus points.</p>",
entities:[{type:"START",pos:[5,5],angle:0.25},{type:"END",box:[350,250,370,270]},{type:"BONUS",pos:[150,150]},{type:"BONUS",pos:[300,50]},{type:"BONUS",pos:[500,125]},{type:"BONUS",pos:[50,320]},{type:"BONUS",pos:[600,350]}]},{name:"Pink Level",url:"levels/easy/pink.png",description:"<p>You might not get all the bonus points on the first try. There is always tomorrow.</p>",entities:[{type:"START",pos:[200,2],angle:0.35},{type:"END",box:[300,200,320,220]},{type:"BONUS",pos:[575,75]},{type:"BONUS",
pos:[440,200]},{type:"BONUS",pos:[535,360]},{type:"BONUS",pos:[100,300]},{type:"BONUS",pos:[170,150]}]},{name:"Orange Level",url:"levels/easy/orange.png",description:"",entities:[{type:"START",pos:[2,164],angle:0},{type:"END",box:[600,350,620,370]},{type:"BONUS",pos:[230,70]},{type:"BONUS",pos:[625,25]},{type:"BONUS",pos:[630,250]},{type:"BONUS",pos:[325,150]},{type:"BONUS",pos:[75,350]},{type:"BONUS",pos:[330,430]},{type:"BONUS",pos:[625,460]},{type:"BONUS",pos:[500,360]}]},{name:"Green Level",url:"levels/easy/green.png",
description:"",entities:[{type:"START",pos:[2,2],angle:0.3},{type:"END",box:[375,200,395,220]},{type:"BONUS",pos:[520,55]},{type:"BONUS",pos:[610,65]},{type:"BONUS",pos:[580,430]},{type:"BONUS",pos:[500,355]},{type:"BONUS",pos:[90,415]},{type:"BONUS",pos:[105,140]},{type:"BONUS",pos:[510,265]},{type:"BONUS",pos:[240,275]}]}]}});a({name:"Hotseat Deathmatch",manifest:{levels:[{name:"Two Players",url:"levels/deathmatch/blank.png",description:"<p>Player 1 controls: Arrow keys</p><p>Player 2 controls: A/S</p>",
is_deathmatch:true,max_players:4,min_players:2},{name:"Three Players",url:"levels/deathmatch/blank.png",description:"<p>Player 1 controls: Arrow keys</p><p>Player 2 controls: A/S</p><p>Player 3 controls: K/L</p>",is_deathmatch:true,max_players:3,min_players:3},{name:"Four Players",url:"levels/deathmatch/blank.png",description:"<p>Player 1 controls: Arrow keys</p><p>Player 2 controls: A/S</p><p>Player 3 controls: K/L</p><p>Player 4 controls: Num Pad</p>",is_deathmatch:true,max_players:4,min_players:4}]}});
hud.draw();hud.show("packs");multiplayer=new Multiplayer(game);game.multiplayer=multiplayer;touchControls=new TouchControls(game)});
